apiVersion: apps/v1
kind: Deployment
metadata:
  name: champion-history
  labels:
    app: champion-history
spec:
  replicas: 1
  selector:
    matchLabels:
      app: champion-history
  template:
    metadata:
      labels:
        app: champion-history
    spec:
      containers:
        - name: champion-history
          image: "username/champion-history:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
