---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: record-search
  labels:
    app: record-search
spec:
  replicas: 1
  selector:
    matchLabels:
      app: record-search
  template:
    metadata:
      labels:
        app: record-search
    spec:
      containers:
        - name: record-search
          image: username/record-search:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: champion-history
  labels:
    app: champion-history
spec:
  replicas: 1
  selector:
    matchLabels:
      app: champion-history
  template:
    metadata:
      labels:
        app: champion-history
    spec:
      containers:
        - name: champion-history
          image: username/champion-history:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: record-search
  labels:
    app: record-search
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: record-search


---


apiVersion: v1
kind: Service
metadata:
  name: champion-history
  labels:
    app: champion-history
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: champion-history

